### ISSUE TITLE
Unable to start tick

### ISSUE THREAD

**Issue by manulachathurika** [KxSystems/kdb-tick#2]
Hi, 

I tried to start the KDB + tick using the following link. I want to do some publisher subscriber program using KDB+ with real time data feed.

https://code.kx.com/q/wp/building_real_time_tick_subscribers.pdf

But when I tried with the command "q tick.q sym C:/OnDiskDB -p 5000" it's giving some syntax issues in the tick.q file.

Could you please elaborate how to run KDB+tick from the beginning.

Thanks !
Manula Thantriwatte

**Comment by CharlieSkelton-Kx** [comment]
there's documentation on tick available at https://github.com/KxSystems/kdb/tree/master/d
